apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  namespace: mardan-smart-city
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
      - name: grafana
        image: grafana/grafana:latest
        ports:
        - containerPort: 3000
        env:
        - name: GF_SECURITY_ADMIN_PASSWORD
          value: "mardan_admin_dashboard"
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "250m"
            memory: "256Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: grafana-service
  namespace: mardan-smart-city
spec:
  selector:
    app: grafana
  ports:
  - port: 3000
    targetPort: 3000
