apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: backend-rolebinding
  namespace: mardan-smart-city
subjects:
- kind: ServiceAccount
  name: backend-sa
  namespace: mardan-smart-city
roleRef:
  kind: Role
  name: backend-role
  apiGroup: rbac.authorization.k8s.io
