apiVersion: v1
kind: ServiceAccount
metadata:
  name: backend-sa
  namespace: mardan-smart-city
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: frontend-sa
  namespace: mardan-smart-city
automountServiceAccountToken: false
