apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: mardan-project
  namespace: argocd
spec:
  description: Mardan Smart City Project
  sourceRepos:
  - 'https://github.com/shoaibikhan-dev/mardan-smart.git'
  destinations:
  - namespace: mardan-smart-city
    server: https://kubernetes.default.svc
  - namespace: monitoring
    server: https://kubernetes.default.svc
  namespaceResourceWhitelist:
  - group: 'apps'
    kind: 'Deployment'
  - group: 'apps'
    kind: 'StatefulSet'
  - group: 'apps'
    kind: 'DaemonSet'
  - group: ''
    kind: 'Service'
  - group: ''
    kind: 'ConfigMap'
  - group: ''
    kind: 'ServiceAccount'
  - group: ''
    kind: 'PersistentVolumeClaim'
  - group: 'networking.k8s.io'
    kind: 'Ingress'
  - group: 'networking.k8s.io'
    kind: 'NetworkPolicy'
  - group: 'autoscaling'
    kind: 'HorizontalPodAutoscaler'
  - group: 'policy'
    kind: 'PodDisruptionBudget'
  - group: 'rbac.authorization.k8s.io'
    kind: 'Role'
  - group: 'rbac.authorization.k8s.io'
    kind: 'RoleBinding'
  - group: 'batch'
    kind: 'CronJob'
  - group: 'bitnami.com'
    kind: 'SealedSecret'
  - group: 'traefik.io'
    kind: 'Middleware'
  clusterResourceWhitelist:
  - group: ''
    kind: 'Namespace'
  roles:
  - name: read-only
    description: Read only access
    policies:
    - p, proj:mardan-project:read-only, applications, get, mardan-project/*, allow
    groups:
    - mardan-viewers
