---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-secret
  namespace: mardan-smart-city
spec:
  encryptedData:
    admin-password: AgBOB6SKLnZzpumUb7AShoCmRDeSBIsTsBCLzs0IsDu4iYKL76s97wMoOV1oDdQ83RDCqkmjpkSHewIviO+v9wLQ3kBhMyYymTZZP5pX14NCTIl1TdUFQIbar4yUXkSlS4eYzDJsb9CjlLFKnlIJo9GjIc3S/1c9vPm2wjEwn46p9pte11aPIkIph8c9+qiC1n2lmBBYFycgJSik78XVDU8x1VLN2LDoy7lPgalwMXP6OD5msxQw22gDC/JQtooJrx4TbAg93DEx7Vls/somnKiGaITRnNVDYBygP7QshJwQCG0YGTqYuct6UDQMc4qZKB0xbZVEg2OxuJUmnIwof1ua35rVtS3QSTRH6uB6DXmXvFO22sPfRvuzaP2933udGoCtTeqwVF52VmcySpAH1He04mMEusagXg7hSTA91Vi9DjP1FtnLx7scj+LqGO5QK1zhr/03XWDT736mTTphOvKmWAKF9zHNPRxVsfbaacnnw8jF/o+NeIrE54TmFFsJN7etyZsYUvFcqFNB7ZdJ91fHfvmMMGngSLa0LnFsdU9OFjnmRzeIiRJf98fc1OoBTQvSHPOuQolB4S9wPZm1kYNAen29Se7t3VwH6MeBLry216NeHws+e5wWBVT8XFiLxd17SXuGtAw3IgTp8rhb59N07LAG+sm4BEmPXC4P3RlO2sTlVtPWf4Y9MsJ6cWiopLgLh+HPvzIdbyXmSU+vkV+RyIOdC977
  template:
    metadata:
      name: grafana-secret
      namespace: mardan-smart-city
    type: Opaque
