name: Cloud-Native Deployment Pipeline
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Login to Container Registry
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERUSERNAME }}
          password: ${{ secrets.DOCKERPASSWORD }}

      - name: Build & Push Backend Docker Image
        run: |
          docker build -t ${{ secrets.DOCKERUSERNAME }}/mardan-backend:latest \
            -t ${{ secrets.DOCKERUSERNAME }}/mardan-backend:${{ github.sha }} ./backend
          docker push ${{ secrets.DOCKERUSERNAME }}/mardan-backend:latest
          docker push ${{ secrets.DOCKERUSERNAME }}/mardan-backend:${{ github.sha }}

      - name: Build & Push Frontend Docker Image
        run: |
          docker build -t ${{ secrets.DOCKERUSERNAME }}/mardan-frontend:latest \
            -t ${{ secrets.DOCKERUSERNAME }}/mardan-frontend:${{ github.sha }} ./frontend
          docker push ${{ secrets.DOCKERUSERNAME }}/mardan-frontend:latest
          docker push ${{ secrets.DOCKERUSERNAME }}/mardan-frontend:${{ github.sha }}
